OUTFILE PEC/PECMETAL_SSB/202506LatestGWAS///res/SCZ_Control6_AA .txt
MARKER Name
ALLELE A1 A2
EFFECT Zval
PVALUE Pval
WEIGHT N
PROCESS PEC/PECJPEGMIX/202506MetalFormat/PGC3_SCZ_wave3.european.autosome.public.v3_AAControl6cisSNP.txt
PROCESS PEC/PECJPEGMIX/202506MetalFormat/SCZ_MVP_aa_AAControl6cisSNP.txt
ANALYZE HETEROGENEITY
